"""Domain entities: RoadmapPhase, Milestone, and Roadmap.

The Roadmap is the central output of the system.
"""

from __future__ import annotations

from datetime import UTC, datetime

from pydantic import BaseModel, Field

from roadmap.domain.entities.learning_resource import LearningResource, Project
from roadmap.domain.entities.skill import Skill
from roadmap.shared.ids import new_id


class Milestone(BaseModel):
    """
    A measurable checkpoint within a roadmap phase.

    Each milestone has concrete exit criteria — a pass/fail checkpoint
    the user can evaluate themselves.
    """

    id: str = Field(default_factory=new_id)
    phase_id: str = Field(default="")
    name: str = Field(min_length=1, max_length=200)
    description: str = Field(default="", max_length=1000)
    exit_criteria: list[str] = Field(
        default_factory=list,
        description="Checklist of observable outcomes that mark this milestone done",
    )
    estimated_weeks: float = Field(default=1.0, ge=0.0)
    is_achieved: bool = Field(default=False)
    achieved_at: datetime | None = Field(default=None)

    def mark_achieved(self) -> None:
        self.is_achieved = True
        self.achieved_at = datetime.now(UTC)


class RoadmapPhase(BaseModel):
    """
    A coherent phase of the learning roadmap.

    Phases group related skills, resources, projects, and milestones
    into a time-bounded learning unit.
    """

    id: str = Field(default_factory=new_id)
    roadmap_id: str = Field(default="")
    phase_number: int = Field(ge=1, description="1-based ordering")

    name: str = Field(min_length=1, max_length=200)
    objective: str = Field(
        default="",
        max_length=500,
        description="What the user will be able to do after this phase",
    )

    # Content
    skills: list[Skill] = Field(default_factory=list)
    resources: list[LearningResource] = Field(default_factory=list)
    projects: list[Project] = Field(default_factory=list)
    milestones: list[Milestone] = Field(default_factory=list)

    estimated_weeks: float = Field(default=4.0, ge=0.0)
    is_completed: bool = Field(default=False)
    completed_at: datetime | None = Field(default=None)

    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def total_estimated_hours(self) -> float:
        skill_hours = sum(s.estimated_hours for s in self.skills)
        resource_hours = sum(r.estimated_hours for r in self.resources)
        project_hours = sum(p.estimated_hours for p in self.projects)
        return skill_hours + resource_hours + project_hours

    @property
    def completion_percentage(self) -> float:
        if not self.skills:
            return 100.0 if self.is_completed else 0.0
        completed = sum(1 for s in self.skills if s.is_completed)
        return (completed / len(self.skills)) * 100.0

    @property
    def skill_names(self) -> list[str]:
        return [s.name for s in self.skills]

    def mark_completed(self) -> None:
        self.is_completed = True
        self.completed_at = datetime.now(UTC)


class Roadmap(BaseModel):
    """
    The complete, structured learning roadmap for a user.

    Generated by the planning agents and stored persistently.
    Contains all phases, skills, resources, projects, and milestones.
    """

    id: str = Field(default_factory=new_id)
    profile_id: str = Field(description="Owning profile ID")

    title: str = Field(
        min_length=1,
        max_length=200,
        description="Human-readable roadmap title",
    )
    version: int = Field(default=1, ge=1, description="Sequential roadmap version (v1, v2, ...)")
    objective: str = Field(default="", description="High-level roadmap goal or mission")
    phases: list[RoadmapPhase] = Field(default_factory=list)

    # Summary metrics
    total_estimated_hours: float = Field(default=0.0, ge=0.0)
    total_weeks: int = Field(default=0, ge=0)

    # Context
    assumptions: list[str] = Field(
        default_factory=list,
        description="Key assumptions made during roadmap generation",
    )
    skipped_skill_names: list[str] = Field(
        default_factory=list,
        description="Skills explicitly deferred or excluded with reasoning",
    )

    # Provenance
    research_run_id: str = Field(
        default="",
        description="ID of the research run that informed this roadmap",
    )
    quality_score: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Assessed multi-dimensional roadmap quality score (0-100)",
    )
    generated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    last_updated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @property
    def overall_completion_percentage(self) -> float:
        if not self.phases:
            return 0.0
        total_skills = sum(len(p.skills) for p in self.phases)
        if total_skills == 0:
            return 0.0
        completed = sum(
            sum(1 for s in p.skills if s.is_completed) for p in self.phases
        )
        return (completed / total_skills) * 100.0

    @property
    def current_phase(self) -> RoadmapPhase | None:
        """Return the first incomplete phase."""
        for phase in self.phases:
            if not phase.is_completed:
                return phase
        return None

    @property
    def completed_phases(self) -> list[RoadmapPhase]:
        return [p for p in self.phases if p.is_completed]

    @property
    def all_skills(self) -> list[Skill]:
        return [skill for phase in self.phases for skill in phase.skills]

    def recalculate_totals(self) -> None:
        """Recompute total hours and weeks from phases."""
        self.total_estimated_hours = sum(
            p.total_estimated_hours for p in self.phases
        )
        self.total_weeks = round(sum(p.estimated_weeks for p in self.phases))
        self.last_updated_at = datetime.now(UTC)


