"""create_llm_budget_and_quota_tables

Revision ID: 881408fd6535
Revises:
Create Date: 2026-09-06 08:19:09.005822

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '881408fd6535'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_states',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('last_failure_category', sa.String(length=100), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_provider_states'))
    )
    op.create_table('llm_usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('workflow', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_category', sa.String(length=100), nullable=True),
    sa.Column('reserved_requests', sa.Integer(), nullable=False),
    sa.Column('actual_requests', sa.Integer(), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage_records'))
    )
    with op.batch_alter_table('llm_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_records_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_records_workflow'), ['workflow'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_workflow'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_records_timestamp'))

    op.drop_table('llm_usage_records')
    op.drop_table('llm_provider_states')
    # ### end Alembic commands ###
