"""add_mvp6_knowledge_intelligence

Revision ID: 94579f682a90
Revises: aaa1f04d5354
Create Date: 2026-09-07 20:58:19.616093

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94579f682a90'
down_revision: str | None = 'aaa1f04d5354'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_knowledge_documents_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_knowledge_documents_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_evidence_id'), ['evidence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_source_id'), ['source_id'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_chunks_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_knowledge_chunks_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('embedding_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('embedding_version', sa.String(length=20), nullable=False),
    sa.Column('vector_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], name=op.f('fk_embedding_records_chunk_id_knowledge_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_embedding_records_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding_records'))
    )
    with op.batch_alter_table('embedding_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_records_chunk_id'), ['chunk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embedding_records_evidence_id'), ['evidence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embedding_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_records_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_embedding_records_chunk_id'))

    op.drop_table('embedding_records')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_content_hash'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_content_hash'))

    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
