"""add_mvp5_progress_feedback_adaptation

Revision ID: aaa1f04d5354
Revises: 1b315108acef
Create Date: 2026-09-07 20:18:24.493053

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aaa1f04d5354'
down_revision: str | None = '1b315108acef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=36), nullable=True),
    sa.Column('skill_name', sa.String(length=200), nullable=False),
    sa.Column('phase_id', sa.String(length=36), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name=op.f('fk_learning_feedbacks_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], name=op.f('fk_learning_feedbacks_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_feedbacks'))
    )
    op.create_table('roadmap_adaptations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('previous_roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('new_roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('previous_version', sa.Integer(), nullable=False),
    sa.Column('new_version', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=500), nullable=False),
    sa.Column('deviation_summary_json', sa.Text(), nullable=False),
    sa.Column('user_feedback_summary_json', sa.Text(), nullable=False),
    sa.Column('changes_summary_json', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['new_roadmap_id'], ['roadmaps.id'], name=op.f('fk_roadmap_adaptations_new_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_roadmap_id'], ['roadmaps.id'], name=op.f('fk_roadmap_adaptations_previous_roadmap_id_roadmaps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name=op.f('fk_roadmap_adaptations_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_adaptations'))
    )
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='NOT_STARTED'))
        batch_op.add_column(sa.Column('planned_hours', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('actual_hours', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_records', schema=None) as batch_op:
        batch_op.drop_column('started_at')
        batch_op.drop_column('actual_hours')
        batch_op.drop_column('planned_hours')
        batch_op.drop_column('status')
        batch_op.drop_column('phase_id')

    op.drop_table('roadmap_adaptations')
    op.drop_table('learning_feedbacks')
    # ### end Alembic commands ###
